seminarioime/config/routes.rb
Rails.application.routes.draw do

  post 'interests', to: 'interests#create'
  delete 'interests', to: 'interests#destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :groups
  resources :seminars, :except => :index

  get "/myarea/attendancelist", :to => 'area#attendance'
  get "/myarea/studentlist", :to => 'area#studentlist'
  get "/myarea/invite", :to => 'area#invite'
  get "/myarea/myseminars", :to => 'area#myseminars'

  post '/myarea/invite', to: 'area#create'

  post 'attendances', to: 'attendances#create'
  get 'attendances/new', to: 'attendances#new'
  get 'attendances/confirm/:rand_token', to: 'attendances#confirm_by_qr'

  get 'users/invite/:rand_token', to: 'invite#new', as: 'new_invite'

  post 'users/invite/:rand_token', to: 'invite#create', as: 'create_invite'

  post 'responsibilities', to: 'responsibilities#create'

  root to: "area#home"
end

seminarioime/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seminarioime</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <strong><%= Rails.application.class.parent_name %></strong>
          </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to 'Groups', groups_path %></li>
             <% if current_user.professor? %>
              <li><%= link_to 'Students', myarea_studentlist_path %></li>
              <li><%= link_to 'My Seminars', myarea_myseminars_path %></li>
              <li><%= link_to 'Invite Professor', myarea_invite_path%></li>
             <% else %>
              <li><%= link_to 'Attended Seminars', myarea_attendancelist_path %></li>
             <% end %>
            <% end %>

            <% if !user_signed_in? %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% else %>
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

            <% end %>

           <!--  <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <br>
        <p class="notice alert alert-info" ><%= notice %></p>
      <% end %>
      <% if alert %>
        <br>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>