seminarioime/config/routes.rb
Rails.application.routes.draw do

  post 'interests', to: 'interests#create'
  delete 'interests', to: 'interests#destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :groups
  resources :seminars, :except => :index

  get "/myarea/attendancelist", :to => 'area#attendance'
  get "/myarea/studentlist", :to => 'area#studentlist'
  get "/myarea/invite", :to => 'area#invite'
  get "/myarea/myseminars", :to => 'area#myseminars'

  post '/myarea/invite', to: 'area#create'

  post 'attendances', to: 'attendances#create'
  get 'attendances/new', to: 'attendances#new'
  get 'attendances/confirm/:rand_token', to: 'attendances#confirm_by_qr'

  get 'users/invite/:rand_token', to: 'invite#new', as: 'new_invite'

  post 'users/invite/:rand_token', to: 'invite#create', as: 'create_invite'

  post 'responsibilities', to: 'responsibilities#create'

  root to: "area#home"
end

seminarioime/app/models/group.rb
class Group < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :seminars
  has_many :users
end

seminarioime/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]


  # GET /groups
  # GET /groups.json
  def index

    if params[:search]
      @groups = Group.where("name like ?", "%#{params[:search]}%")
    else @groups = Group.all end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @my_seminars = @group.seminars
    print (@group.users.size)
    print (@group.seminars.size)
  end

  # GET /groups/new
  def new
    if user_signed_in? && current_user.student?
      redirect_to action: "index"
      flash[:notice] = "Only logged Professors can create new groups."
      return
    end
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    if user_signed_in? && current_user.student?
      redirect_to action: "index"
      flash[:notice] = "Only logged Professors can edit groups."
      return
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    if not current_user.usertype
      respond_to do |format|
        format.html { redirect_to (@group) , notice: 'You dont have permission to create a group.' and return}
        format.json { render :show, status: :unprocessable_entity, location: @group }
      end
    end
    

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
     
    if not current_user.usertype
      respond_to do |format|
        format.html { redirect_to groups_url , notice: 'You dont have permission to edit a group.' and return}
        format.json { render :show, status: :unprocessable_entity, location: @group }
      end
    end

    
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    if (@group.seminars.size > 0 or @group.users.size > 0)
      redirect_to action: "index"
      flash[:notice] = "You can't destroy this group. There are seminars or students in it."
      return
    end
    if not current_user.usertype
      respond_to do |format|
        format.html { redirect_to groups_url , notice: 'You dont have permission to remove a group.' and return}
        format.json { render :show, status: :unprocessable_entity, location: @group }
      end
    end
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

seminarioime/app/helpers/groups_helper.rb
module GroupsHelper
end

seminarioime/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <%=
        if group.errors.count == 1
          "Ops! There was #{group.errors.count} error:"
        else
          "Ops! There where #{group.errors.count} errors:"
        end
      %>
      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :group_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-info btn-block" %>
  </div>
<% end %>

seminarioime/app/views/groups/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Editing Group</h1>

    <%= render 'form', group: @group %>

  </div>
</div>

seminarioime/app/views/groups/index.html.erb
<h1>Groups</h1>


<%= form_tag(groups_path, :method => "get", id: "search-form") do %>
   <div class="input-group">
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <span class="input-group-btn">
        <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
    </span>
  </div>
<% end %>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <% if user_signed_in? and current_user.professor? %>
        <th colspan="2">Options</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |datum| %>
      <tr>
        <% if user_signed_in? and current_user.professor? %>
          <td class="col-md-8 clickable" onmouseout="hover(this,false)" onmouseover="hover(this,true)" onclick="goto('<%= datum.id %>')">
            <%= datum.name %>
          </td>
          <td class="col-md-2"><%= link_to 'Edit', edit_group_path(datum), class: "btn btn-primary btn-sm" %></td>
          <td class="col-md-2"><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %></td>
      <% else %>
        <td class="clickable" onmouseout="hover(this,false)" onmouseover="hover(this,true)" onclick="goto('<%= datum.id %>')">
          <%= datum.name %>
        </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.professor? %>
   <%= link_to 'New Group', new_group_path, class: "btn btn-default" %>
<% end %>

<style>
.clickable {
  cursor: pointer;
}
</style>

<script>
  function goto (to) {
    var base = '<%= request.base_url + '/groups/' %>';
    window.location.href = base + to;
  }
  function hover (bt, cond) {
    bt.style.backgroundColor =  cond ? "#ECF0F1" : "white";
  }
</script>

seminarioime/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

seminarioime/app/views/groups/show.html.erb
<h1>Seminars from the group "<%= @group.name %>"</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Place</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_seminars.each do |datum| %>
      <tr class="clickable" onclick="trcli(this)" data-href="<%= request.base_url + '/seminars/' + String(datum.id) %>">
        <td><%= datum.name %></td>
        <td><%= datum.description %></td>
        <td><%= datum.place %></td>
        <td><%= datum.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= if current_user.professor? then link_to 'Edit', edit_group_path(@group), class: "btn btn-default" end %>
<%= link_to 'Back', groups_path, class: "btn btn-default" %>

<style>
.clickable {
  cursor: pointer;
}
</style>

<script>
  function trcli (bt) {
    window.location.href = bt.getAttribute ("data-href");
  }
</script>