seminarioime/config/routes.rb
Rails.application.routes.draw do

  post 'interests', to: 'interests#create'
  delete 'interests', to: 'interests#destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :groups
  resources :seminars, :except => :index

  get "/myarea/attendancelist", :to => 'area#attendance'
  get "/myarea/studentlist", :to => 'area#studentlist'
  get "/myarea/invite", :to => 'area#invite'
  get "/myarea/myseminars", :to => 'area#myseminars'

  post '/myarea/invite', to: 'area#create'

  post 'attendances', to: 'attendances#create'
  get 'attendances/new', to: 'attendances#new'
  get 'attendances/confirm/:rand_token', to: 'attendances#confirm_by_qr'

  get 'users/invite/:rand_token', to: 'invite#new', as: 'new_invite'

  post 'users/invite/:rand_token', to: 'invite#create', as: 'create_invite'

  post 'responsibilities', to: 'responsibilities#create'

  root to: "area#home"
end

seminarioime/app/controllers/area_controller.rb
class AreaController < ApplicationController
  before_action :authenticate_user!, except: [:home]

  def invite
    if user_signed_in? && current_user.student?
      redirect_to root_path
      flash[:notice] = "Only logged professors can invite professors."
      return
    end
    @professors = Professor.new
  end

  def create
    @rand_string = SecureRandom.base58(60)
    if (User.find_by_email(professor_params) != nil)
      flash[:notice] = "Email already registered"
      redirect_to myarea_invite_path and return
    end
    if (Professor.find_by_email(professor_params) != nil)
      flash[:notice] = "Invite already sent"
      redirect_to myarea_invite_path and return
    end
    @professors = Professor.new(:email => professor_params, :token => @rand_string, :register => false)
    if user_signed_in? && current_user.professor?
      @professors.save
      @base = request.base_url
      if @base.include? "localhost"
        @iplocal = Socket.ip_address_list[1].ip_address
        @base = "http://"+@iplocal+":3000"
      end
      @reg_link = @base+"/users/invite/"+@rand_string
      UserNotifierMailer.send_email(@professors, @reg_link).deliver
      flash[:notice] = "You invited a new professor"
      redirect_to root_path
    end
  end

  def home
    if params[:search]
      @seminars = Seminar.where("name like ?", "%#{params[:search]}%")
    else @seminars = Seminar.all end

    if user_signed_in? && current_user.student?
      @interested = current_user.interests.map {|i| i.seminar}
      @seminars = @seminars.reject {|s| @interested.include? (s) }
    end
  end

  def attendance
    unless user_signed_in? && current_user.student?
      redirect_to action: "home"
      return
    end
    @user = current_user
    year = Date.today.year
    half_year = Date.new(year,7,20)

    if Date.new() > half_year
      interval = half_year..Date.new(year,12,-1)
    else
      interval = Date.new(year,1,1)..half_year
    end

    @attendences_in_semester = @user.attendances.where(updated_at: interval).count
  end

  def myseminars
    unless user_signed_in? && current_user.professor?
      redirect_to action: "home"
    end
    @seminars = current_user.mySeminars
  end

  def studentlist
    unless user_signed_in? && current_user.professor?
      redirect_to action: "home"
      return
    end
    if params[:search]
      @students = User.where("name like ?", "%#{params[:search]}%")
      @students = @students.select {|student| student.usertype == false}
    else @students = User.where(:usertype => false) end

  end
  private
  # Use callbacks to share common setup or constraints between actions.
    def professor_params
      params.require(:email)
    end
end

seminarioime/app/helpers/area_helper.rb
module AreaHelper
end

seminarioime/app/views/area/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control", autofocus: "autofocus" %>
  </div>

  <%= form.submit "Send Invititation", class: "btn  btn-default" %>
<% end %>

seminarioime/app/views/area/attendance.html.erb
<h1>My Attendance List</h1>
<hr>

<div class="row">
  <div class="col-md-8">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Seminar Name</th>
          <th>Group</th>
          <th>Seminar Date</th>
          <th>Attendance Date</th>
          <th>Professor</th>
        </tr>
      </thead>

      <tbody>
        <% @user.attendances.each do |attendance| %>
          <tr>
            <td>
              <%= link_to attendance.seminar.name, attendance.seminar %>
            </td>
            <td><%= attendance.seminar.group.name %></td>
            <td><%= attendance.seminar.date %></td>
            <td><%= attendance.updated_at %></td>
            <td><%= attendance.responsibility.user.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4", style="text-align: center">
    <div style="font-size: 80px">
      <%= @attendences_in_semester%>
    </div>
    <small>Attendances completed in this semester.</small>
  </div>
</div>

seminarioime/app/views/area/home.html.erb
<% if user_signed_in? %>
  <h1>My Area</h1>

  <hr>

  <% if current_user.student? %>
    <h3>Interested Seminars</h3>
    <% if @interested.empty? %>
      <p>You don't have interests</p>
    <% else %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Group</th>
            <th>Description</th>
            <th>Place</th>
            <th>Date</th>
          </tr>
        </thead>

        <tbody>
          <% @interested.each do |i| %>
            <tr class="clickable" onclick="goto('<%= i.id %>')">
              <td><%= i.name %></td>
              <td><%= i.group.name %></td>
              <td><%= truncate(i.description, length: 300) %></td>
              <td><%= i.place %></td>
              <td><%= i.date %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <hr>
  <% end %>

  <h3>All Seminars</h3>
<% else %>
  <h1>Seminars</h1>
  <hr>
<% end %>

<%= form_tag(root_path, :method => "get", id: "search-form") do %>
   <div class="input-group", style="margin-bottom: 25px">
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <span class="input-group-btn">
      <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
    </span>
  </div>
<% end %>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Description</th>
      <th>Place</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @seminars.each do |s| %>
      <tr class="clickable" onclick="goto('<%= s.id %>')">
        <td><%= s.name %></td>
        <td><%= s.group.name %></td>
        <td><%= truncate(s.description, length: 300) %></td>
        <td><%= s.place %></td>
        <td><%= s.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? && current_user.professor? %>
    <%= link_to 'New Seminar', new_seminar_path, class: "btn btn-default" %>
<% end %>


<script>
function goto (to) {
  var base = '<%= request.base_url + '/seminars/' %>';
  window.location.href = base + to;
}
</script>

<style>
.clickable {
  cursor: pointer;
}
</style>

seminarioime/app/views/area/invite.html.erb
<h1>Professor Invititation</h1>
<hr>

<div class="row">
    <div class="col-md-6">
        <ul>
          <li>Register the new professor's email in the form below.</li>
          <li>Tell the new Professor he/she can sign up normally.</li>
          <li>After his/her sign up, his/her condition will be automatically set.</li>
        </ul>
    </div>
    <div  class="col-md-6">
        <%= render 'form', professor: @professor %>
    </div>
</div>

seminarioime/app/views/area/myseminars.html.erb
<h1> My Seminars </h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Description</th>
      <th>Place</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seminars.each do |seminar| %>
      <tr>
        <td><%= seminar.name %></td>
        <td><%= seminar.group.name %></td>
        <td><%= seminar.description %></td>
        <td><%= seminar.place %></td>
        <td><%= seminar.date %></td>
        <td><%= link_to 'Show', seminar %></td>
      </tr>
    <% end %>
  </tbody>
</table>

seminarioime/app/views/area/studentlist.html.erb
<h1>My Student List</h1>

<%= form_tag(myarea_studentlist_path, :method => "get", id: "search-form") do %>
   <div class="input-group">
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <span class="input-group-btn">
        <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
    </span>
  </div>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>nusp</th>
      <th>email</th>
      <th>Attendances</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.nusp %></td>
        <td><%= student.email %></td>
        <td><%= student.attendedSeminars.length %></td>
      </tr>
    <% end %>
  </tbody>
</table>