seminarioime/config/routes.rb
Rails.application.routes.draw do

  post 'interests', to: 'interests#create'
  delete 'interests', to: 'interests#destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :groups
  resources :seminars, :except => :index

  get "/myarea/attendancelist", :to => 'area#attendance'
  get "/myarea/studentlist", :to => 'area#studentlist'
  get "/myarea/invite", :to => 'area#invite'
  get "/myarea/myseminars", :to => 'area#myseminars'

  post '/myarea/invite', to: 'area#create'

  post 'attendances', to: 'attendances#create'
  get 'attendances/new', to: 'attendances#new'
  get 'attendances/confirm/:rand_token', to: 'attendances#confirm_by_qr'

  get 'users/invite/:rand_token', to: 'invite#new', as: 'new_invite'

  post 'users/invite/:rand_token', to: 'invite#create', as: 'create_invite'

  post 'responsibilities', to: 'responsibilities#create'

  root to: "area#home"
end

seminarioime/app/models/seminar.rb
class Seminar < ApplicationRecord
  belongs_to :group
  has_many :responsibilities
  has_many :users, through: :responsibilities
  has_many :attendances, through: :responsibilities
  has_many :interests

  validates :name, uniqueness: :true, presence: true
  validates :date, presence: true, :allow_blank => false
  validates :place, presence: true, :allow_blank => false
  validates_length_of :description, :minimum => 20, :allow_blank => false

end

seminarioime/app/controllers/seminars_controller.rb
class SeminarsController < ApplicationController
  before_action :set_seminar, only: [:show, :edit, :update, :destroy]

  # GET /seminars/1
  # GET /seminars/1.json
  def show
    if user_signed_in? && current_user.student?
      @interest = Interest.find_by(seminar_id: @seminar.id,
                                   user_id: current_user.id)
    end

    @interest_count = Interest.where(seminar_id: @seminar.id).length
  end

  # GET /seminars/new
  def new
    unless user_signed_in? && current_user.professor?
      flash[:notice] = "Only logged Professors can create new seminars."
      redirect_to '/'
      return
    end

    @seminar = Seminar.new
  end

  # GET /seminars/1/edit
  def edit
    unless user_signed_in? && current_user.responsibilities.exists?(seminar_id: @seminar.id)
      flash[:notice] = "Only logged Professors can edit seminars."
      redirect_to '/'
      return
    end
  end

  # POST /seminars
  # POST /seminars.json
  def create
    unless user_signed_in? && current_user.professor?
      redirect_to '/'
      return
    end

    @seminar = Seminar.new(seminar_params)

    if @seminar.valid?
      respond_to do |format|
        if @seminar.save
          current_user.responsibilities.create!(seminar_id: @seminar.id)
          @users = User.all
          @users.each { |user|
            UserNotifierMailer.created_seminar(user, @seminar).deliver
          }
          format.html { redirect_to @seminar, notice: 'Seminar was successfully created.' }
          format.json { render :show, status: :created, location: @seminar }
        else
          format.html { render :new }
          format.json { render json: @seminar.errors, status: :unprocessable_entity }
        end
      end
    else
      @groups = Group.all.map {|group| [group.name, group.id]}
      render :new
    end
  end

  # PATCH/PUT /seminars/1
  # PATCH/PUT /seminars/1.json
  def update
    unless user_signed_in? && current_user.responsibilities.exists?(seminar_id: @seminar.id)
      redirect_to '/'
      return
    end

    respond_to do |format|
      if @seminar.update(seminar_params)

        @interests = @seminar.interests
        @interests.each { |interest|
          UserNotifierMailer.updated_seminar(interest.user, @seminar).deliver
        }
        format.html { redirect_to @seminar, notice: 'Seminar was successfully updated.' }
        format.json { render :show, status: :ok, location: @seminar }

      else
        format.html { render :edit }
        format.json { render json: @seminar.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /seminars/1
  # DELETE /seminars/1.json
  def destroy

    unless user_signed_in? && current_user.responsibilities.exists?(seminar_id: @seminar.id)
      redirect_to '/'
      return
    end

    if ( @seminar.attendances.size > 0)
      flash[:notice] = "You can't destroy this group. There are seminars or students in it."
      redirect_to '/'
      return
    end


    @seminar.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Seminar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seminar
      @seminar = Seminar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seminar_params
      params.require(:seminar).permit(:seminar_id, :group_id, :name, :description, :place, :date)
    end
end

seminarioime/app/helpers/seminars_helper.rb
module SeminarsHelper
end

seminarioime/app/views/seminars/_form.html.erb
<%= form_with(model: seminar, local: true) do |form| %>
  <% if seminar.errors.any? %>
    <div>
      <% seminar.errors.full_messages.each do |message| %>
        <p class="alert alert-danger"><%= message %></p>
      <% end %>
    </div>
  <% end %>

    <div class="field form-group">
        <%= label_tag("seminar[name]", "Name") %>
        <%= text_field_tag("seminar[name]", @seminar.name, class: "form-control") %>
    </div>

    <div class="field form-group">
        <%= label_tag("seminar[group_id]", "Group") %>
        <%= collection_select :seminar, :group_id, Group.all, :id, :name, {}, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= label_tag("seminar[description]", "Description") %>
        <%= text_area_tag("seminar[description]", @seminar.description, class: "form-control",  rows: 10)    %>
    </div>

    <div class="field form-group">
        <%= label_tag("seminar[place]", "Place") %>
        <%= text_field_tag("seminar[place]", @seminar.place, class: "form-control") %>
    </div>

    <div class="field form-group">
        <%= label_tag("seminar[date]", "Date") %>
        <div class='input-group date' id='datetimepicker1'>
            <%= text_field_tag("seminar[date]", @seminar.date, class: "form-control") %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            <%= form.submit 'Save', class: "btn btn-default btn-block" %>
        </div>
    </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({ format: 'YYYY-MM-DD HH:mm' });
    });
</script>

seminarioime/app/views/seminars/_resposible_professors.html.erb
<table class="table table-bordered table-striped">
    <thead>
        <th>Name</th>
    </thead>
    <tbody>
        <% @seminar.responsibilities.each do |responsibility| %>
            <tr>
                <td><%= responsibility.user.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>

seminarioime/app/views/seminars/edit.html.erb
<h1>Editing Seminar</h1>

<%= render 'form', seminar: @seminar %>

<hr>
<%= form_tag("/responsibilities", method: "post") do %>
    <%= label_tag("user_id", "Professor NUSP") %><br>
    <%= hidden_field_tag("seminar_id", @seminar.id) %>
    <div class='input-group' id='datetimepicker1'>
        <%= collection_select nil, :user_id, User.all.where(usertype: User.professor), :id, :name, {:include_blank => ""}, class: "form-control" %>
        <span class="input-group-btn">
            <%= submit_tag("Add Professor", class: "btn btn-default") %>
        </span>
    </div>

<% end %>

<br>
<%= render 'resposible_professors', seminar: @seminar %>

seminarioime/app/views/seminars/new.html.erb
<h1>New Seminar</h1>

<%= render 'form', seminar: @seminar %>

seminarioime/app/views/seminars/show.html.erb
<h2> <%= @seminar.name %></h2>
<hr>

<div class="row">
    <div class="col-md-8">
        <div class="jumbotron">
            <%= @seminar.description %>
        </div>
        <table class="table">
            <tr>
                <td><strong>Group:</strong></td>
                <td><%= @seminar.group.name %></td>
            </tr>
            <tr>
                <td><strong>Place:</strong></td>
                <td><%= @seminar.place %></td>
            </tr>
            <tr>
                <td><strong>Date:</strong></td>
                <td><%= @seminar.date %></td>
            </tr>
        </table>
    </div>
    <div class="col-md-4">
        <div style="text-align: center">
            <div style="font-size: 80px">
              <%= @interest_count %>
            </div>
            <small>Number of interested people.</small>
        </div>
        <br>
        <% if current_user && current_user.responsibilities.exists?(seminar_id: @seminar.id) %>
            <div class="btn-group-vertical btn-block">

                <%= link_to 'Confirm Attendances', attendances_new_path(seminar_id: @seminar.id), class: "btn btn-success"%>
                <%= link_to 'Edit', edit_seminar_path(@seminar), class: "btn btn-info" %>
                <%= link_to 'Destroy', @seminar, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
        <% end %>
    </div>
</div>

<% if user_signed_in? && current_user.student? %>
    <% if @interest %>
        <%= form_tag("/interests", method: :delete) do %>
            <%= hidden_field_tag("interest_id", @interest.id) %>
            <%= submit_tag "Unsubscribe", class: "btn btn-default" %>
        <% end %>
    <% else %>
        <%= form_tag("/interests", method: :post) do %>
            <%= hidden_field_tag("seminar_id", @seminar.id) %>
            <%= submit_tag "Subscribe", class: "btn btn-info" %>
        <% end %>
    <% end %>
<% end %>

<hr>
<h4> Responsible Professors </h4>
<%= render 'resposible_professors', seminar: @seminar %>

<% if user_signed_in? && current_user.professor? && @seminar.attendances.length > 0 %>
    <hr>
    <h4> Attended Students </h4>
    <table class="table table-bordered table-striped">
        <thead>
            <th>NUSP</th>
            <th>Name</th>
            <th>Validated by</th>
        </thead>
        <tbody>
            <% @seminar.attendances.each do |attendance| %>
                <% if !attendance.user.nil? %>
                    <tr>
                        <td><%= attendance.user.nusp %></td>
                        <td><%= attendance.user.name %></td>
                        <td><%= attendance.responsibility.user.name %></td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
<% end %>